"""init schema

Revision ID: c0b4207319da
Revises:
Create Date: 2026-04-27 08:45:09.251694

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0b4207319da"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("train_ids", sa.JSON(), nullable=False),
        sa.Column("val_ids", sa.JSON(), nullable=False),
        sa.Column("test_ids", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("domain", sa.String(length=256), nullable=False),
        sa.Column("rss_urls", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("robots_ok", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sources_source_id"), ["source_id"], unique=True)

    op.create_table(
        "articles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_fk", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("url_hash", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=1024), nullable=False),
        sa.Column("author", sa.String(length=256), nullable=True),
        sa.Column("category", sa.String(length=128), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("raw_html_path", sa.String(length=512), nullable=True),
        sa.Column("content_text", sa.Text(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("simhash", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["source_fk"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    with op.batch_alter_table("articles", schema=None) as batch_op:
        batch_op.create_index("ix_articles_published_at_desc", ["published_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_articles_simhash"), ["simhash"], unique=False)
        batch_op.create_index(batch_op.f("ix_articles_source_fk"), ["source_fk"], unique=False)
        batch_op.create_index(batch_op.f("ix_articles_status"), ["status"], unique=False)
        batch_op.create_index("ix_articles_status_pub", ["status", "published_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_articles_url_hash"), ["url_hash"], unique=True)

    op.create_table(
        "crawl_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_fk", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("n_new", sa.Integer(), nullable=False),
        sa.Column("n_skipped", sa.Integer(), nullable=False),
        sa.Column("n_errors", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["source_fk"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("crawl_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_crawl_runs_source_fk"), ["source_fk"], unique=False)

    op.create_table(
        "model_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("params", sa.JSON(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column("artifact_path", sa.String(length=512), nullable=True),
        sa.Column("dataset_version_fk", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_version_fk"], ["dataset_versions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_name", "version", name="uq_model_runs_name_version"),
    )
    op.create_table(
        "labels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("article_fk", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=True),
        sa.Column("reviewer_id", sa.String(length=64), nullable=True),
        sa.Column("quality", sa.String(length=16), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("qc_passed", sa.Boolean(), nullable=False),
        sa.Column("qc_details", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["article_fk"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("labels", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_labels_article_fk"), ["article_fk"], unique=False)

    op.create_table(
        "summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("article_fk", sa.Integer(), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=True),
        sa.Column("rouge1", sa.Float(), nullable=True),
        sa.Column("rouge2", sa.Float(), nullable=True),
        sa.Column("rougeL", sa.Float(), nullable=True),
        sa.Column("bertscore_f1", sa.Float(), nullable=True),
        sa.Column("factuality_score", sa.Float(), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["article_fk"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("summaries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_summaries_article_fk"), ["article_fk"], unique=False)
        batch_op.create_index(
            "ix_summaries_article_pub", ["article_fk", "is_published"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_summaries_is_published"), ["is_published"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("summaries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_summaries_is_published"))
        batch_op.drop_index("ix_summaries_article_pub")
        batch_op.drop_index(batch_op.f("ix_summaries_article_fk"))

    op.drop_table("summaries")
    with op.batch_alter_table("labels", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_labels_article_fk"))

    op.drop_table("labels")
    op.drop_table("model_runs")
    with op.batch_alter_table("crawl_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_crawl_runs_source_fk"))

    op.drop_table("crawl_runs")
    with op.batch_alter_table("articles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_articles_url_hash"))
        batch_op.drop_index("ix_articles_status_pub")
        batch_op.drop_index(batch_op.f("ix_articles_status"))
        batch_op.drop_index(batch_op.f("ix_articles_source_fk"))
        batch_op.drop_index(batch_op.f("ix_articles_simhash"))
        batch_op.drop_index("ix_articles_published_at_desc")

    op.drop_table("articles")
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sources_source_id"))

    op.drop_table("sources")
    op.drop_table("dataset_versions")
    # ### end Alembic commands ###
